### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: input.flat is not a function

### ISSUE THREAD

**Issue by zrysmt** [philcockfield/file-system-cache#15]
version: 1.1.0

```
(node:347) UnhandledPromiseRejectionWarning: TypeError: input.flat is not a function
    at compact (/cloud/source_code/node_modules/_file-system-cache@1.1.0@file-system-cache/lib/common/Util.js:23:18)
    at /cloud/source_code/node_modules/_ramda@0.28.0@ramda/src/internal/_pipe.js:3:27
    at /cloud/source_code/node_modules/_ramda@0.28.0@ramda/src/internal/_arity.js:11:19
    at Object.hash (/cloud/source_code/node_modules/_file-system-cache@1.1.0@file-system-cache/lib/common/Util.js:46:57)
    at new FileSystemCache (/cloud/source_code/node_modules/_file-system-cache@1.1.0@file-system-cache/lib/FileSystemCache.js:18:33)
    at exports.default (/cloud/source_code/node_modules/_file-system-cache@1.1.0@file-system-cache/lib/index.js:6:32)
    at Object.<anonymous> (/cloud/source_code/node_modules/_@storybook_core@5.3.21@@storybook/core/dist/server/build-dev.js:74:44)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/cloud/source_code/node_modules/_pirates@4.0.5@pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/cloud/source_code/node_modules/_pirates@4.0.5@pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by rasheedherel1** [comment]
Same issue since the update of 1.1.0 and onwards. 

"file-system-cache": "1.0.5" as a dev dependency as a work around. @zrysmt
